// Atlas Obscura places in Scotland
// Sourced from atlasobscura.com search endpoint - see ATLAS_OBSCURA_DATA.md
const ATLAS_OBSCURA_PLACES = [
  // === Edinburgh ===
  { name: "Blair Street Underground Vaults", lat: 55.949647, lng: -3.190193, description: "A labyrinthine network of chambers with a storied past hides below Edinburgh's South Bridge.", url: "https://www.atlasobscura.com/places/blair-street-underground-vaults" },
  { name: "The Lost Close", lat: 55.949571, lng: -3.189713, description: "An underground venue, buried for 200 years, now open as a unique whisky tasting venue.", url: "https://www.atlasobscura.com/places/the-lost-close" },
  { name: "James Braidwood Statue", lat: 55.949508, lng: -3.189984, description: "Dedicated to the Father of the British Fire Service.", url: "https://www.atlasobscura.com/places/james-braidwood-statue" },
  { name: "Roxburgh Court Tree Plaques", lat: 55.950197, lng: -3.191011, description: "Plaques in a court preserve a small piece of Edinburgh's history.", url: "https://www.atlasobscura.com/places/roxburgh-court-tree-plaques" },
  { name: "St Giles' Cathedral Thistle Chapel", lat: 55.949364, lng: -3.190411, description: "The chapel's intricate woodwork includes amazing details, most notably angels playing bagpipes.", url: "https://www.atlasobscura.com/places/st-giles-cathedral-thistle-chapel" },
  { name: "The Cutty Stool", lat: 55.949484, lng: -3.190892, description: "A bronze statue of a low three-legged seat commemorates a piece of furniture that started a riot.", url: "https://www.atlasobscura.com/places/cutty-stool-edinburgh" },
  { name: "Charles II Statue", lat: 55.949243, lng: -3.190519, description: "Edinburgh's oldest statue hides within a parking lot behind the city's iconic cathedral.", url: "https://www.atlasobscura.com/places/charles-ii-statue" },
  { name: "John Knox's Grave", lat: 55.949219, lng: -3.190708, description: "The Scottish Reformation leader's grave was paved over and is now a parking lot.", url: "https://www.atlasobscura.com/places/john-knoxs-grave" },
  { name: "Mary King's Close", lat: 55.950081, lng: -3.188237, description: "17th century streets hidden under Edinburgh were once a breeding ground for the black death.", url: "https://www.atlasobscura.com/places/mary-kings-close" },
  { name: "The Heart of Midlothian", lat: 55.949634, lng: -3.191865, description: "A sweet symbol marks the place where torturous executions were once carried out.", url: "https://www.atlasobscura.com/places/the-heart-of-midlothian-edinburgh-scotland" },
  { name: "David Hume's Statue", lat: 55.949564, lng: -3.192441, description: "Touching this 18th-century Scottish philosopher's toe allegedly conjures good fortune.", url: "https://www.atlasobscura.com/places/david-humes-statue" },
  { name: "The Scotsman Steps", lat: 55.951171, lng: -3.188506, description: "The colorful stairs are made with marble from the world's major quarries.", url: "https://www.atlasobscura.com/places/the-scotsman-steps" },
  { name: "Wardrop's Court Dragons", lat: 55.949371, lng: -3.193131, description: "A quartet of brightly colored mythical beasts stand sentry at this gateway.", url: "https://www.atlasobscura.com/places/wardrops-court-dragons" },
  { name: "The Martyrs' Cross", lat: 55.951191, lng: -3.18711, description: "This metallic cross was most likely the last thing a condemned person would see on the gallows.", url: "https://www.atlasobscura.com/places/martyrs-cross" },
  { name: "Luckenbooths", lat: 55.950342, lng: -3.186297, description: "Brass bricks outline the locations of Edinburgh's lost, lively market stalls.", url: "https://www.atlasobscura.com/places/luckenbooths" },

  // === Edinburgh Wider Area ===
  { name: "Huly Hill", lat: 55.938538, lng: -3.404876, description: "Prehistoric site visible from Edinburgh Airport.", url: "https://www.atlasobscura.com/places/huly-hill" },
  { name: "Jupiter Artland", lat: 55.901043, lng: -3.421217, description: "Contemporary artworks across fields and forests near a Jacobean manor.", url: "https://www.atlasobscura.com/places/jupiter-artland" },
  { name: "William Wallace Marker", lat: 55.91579, lng: -3.459181, description: "Possibly oldest Scottish memorial to the 13th-century knight.", url: "https://www.atlasobscura.com/places/william-wallace-marker" },
  { name: "The Burryman", lat: 55.989803, lng: -3.393727, description: "800-year-old tradition featuring a man parading in a spiky burrs costume.", url: "https://www.atlasobscura.com/places/burryman-scotland" },
  { name: "The Black Castle", lat: 55.989891, lng: -3.394975, description: "Severely painted building with connections to 1640s witch hunts.", url: "https://www.atlasobscura.com/places/the-black-castle" },
  { name: "Forth Bridge", lat: 56.000649, lng: -3.388439, description: "Victorian engineering feat spanning Firth of Forth.", url: "https://www.atlasobscura.com/places/forth-railway-bridge" },
  { name: "Sir Nils Olav", lat: 55.942175, lng: -3.26933, description: "King penguin serving as knighted brigadier of the Norwegian Army.", url: "https://www.atlasobscura.com/places/sir-nils-olav" },
  { name: "Barnton Quarry Nuclear Bunker", lat: 55.9591, lng: -3.277965, description: "Abandoned underground complex designed for royal Cold War refuge.", url: "https://www.atlasobscura.com/places/barnton-quarry-nuclear-bunker" },
  { name: "Eagle Rock", lat: 55.98293, lng: -3.308706, description: "Evidence of Roman military presence on the Scottish coast.", url: "https://www.atlasobscura.com/places/roman-eagle-rock" },
  { name: "The Loony Dook", lat: 55.992778, lng: -3.386667, description: "New Year's Day tradition of costumed swimming in the Firth of Forth.", url: "https://www.atlasobscura.com/places/the-loony-dook" },

  // === Glasgow ===
  { name: "George Square Imperial Measurements", lat: 55.860716, lng: -4.249031, description: "A small collection of objects of a bygone era hide in plain view.", url: "https://www.atlasobscura.com/places/george-square-imperial-measurements" },
  { name: "Duke of Wellington Statue", lat: 55.860102, lng: -4.252, description: "This stately monument has been wearing a traffic cone hat for decades.", url: "https://www.atlasobscura.com/places/duke-of-wellington-statue" },
  { name: "Glasgow City Chambers' Staircase", lat: 55.860922, lng: -4.248262, description: "The ornate structure is part of a building boasting more marble than the Vatican.", url: "https://www.atlasobscura.com/places/glasgow-city-chambers-staircase" },
  { name: "Hutchesons' Hall Statues", lat: 55.85986, lng: -4.247546, description: "A brother statue swap has adorned this building's facade for centuries.", url: "https://www.atlasobscura.com/places/hutchesons-hall-statues-glasgow-scotland" },
  { name: "The Lighthouse", lat: 55.859798, lng: -4.255139, description: "Climb this overlooked gem's spiral staircase for spectacular views of Glasgow.", url: "https://www.atlasobscura.com/places/the-lighthouse-glasgow" },
  { name: "Unmarked Grave of Pierre Emile L'Angelier", lat: 55.860184, lng: -4.244705, description: "Final resting place of a poisoned lover at the center of one of Glasgow's most sensational murder trials.", url: "https://www.atlasobscura.com/places/the-unmarked-grave-of-pierre-emile-langelier" },
  { name: "Britannia Panopticon Music Hall", lat: 55.857213, lng: -4.247066, description: "The world's oldest surviving music hall was also once a freakshow.", url: "https://www.atlasobscura.com/places/britannia-panopticon-music-hall" },
  { name: "Sharmanka Kinetic Theatre", lat: 55.857055, lng: -4.246801, description: "Elaborate clockwork contraptions create small worlds of whimsy and horror.", url: "https://www.atlasobscura.com/places/sharmanka-kinetic-theatre" },
  { name: "Glasgow Police Museum", lat: 55.857958, lng: -4.244897, description: "This hidden gem reveals the history of Britain's first police force.", url: "https://www.atlasobscura.com/places/the-glasgow-police-museum" },
  { name: "Empire Neon Sign", lat: 55.856561, lng: -4.247308, description: "This neon sign is an homage to an Alfred Hitchcock film.", url: "https://www.atlasobscura.com/places/empire-sign-glasgow" },
  { name: "Rottenrow Gardens", lat: 55.861948, lng: -4.244062, description: "A serene public space nestled within remains of Glasgow's Victorian maternity hospital.", url: "https://www.atlasobscura.com/places/rottenrow-gardens" },
  { name: "The Trongate Cherub", lat: 55.856752, lng: -4.24491, description: "An angelic yet demonic-looking figurine presides over one of Glasgow's most ancient streets.", url: "https://www.atlasobscura.com/places/the-trongate-cherub" },
  { name: "The Highlandman's Umbrella", lat: 55.859112, lng: -4.258109, description: "Displaced highlanders sheltered from the wet Scottish climate under this bridge.", url: "https://www.atlasobscura.com/places/the-highlandmans-umbrella-glasgow-scotland" },
  { name: "The Scotia Bar", lat: 55.8553, lng: -4.250306, description: "Glasgow's oldest pub has a proud literary tradition and possibly a ghost or two.", url: "https://www.atlasobscura.com/places/scotia-bar" },
  { name: "Glasgow City Center Mural Trail", lat: 55.857526, lng: -4.257528, description: "A scattered trail of street art adds a pop of color to the city.", url: "https://www.atlasobscura.com/places/glasgow-city-center-mural-trail" },

  // === Stirling ===
  { name: "Mar's Wark", lat: 56.121137, lng: -3.944181, description: "The main residence of the Erskine family and hereditary keeper of Stirling Castle.", url: "https://www.atlasobscura.com/places/mars-wark" },
  { name: "Cowane's Hospital", lat: 56.120849, lng: -3.944459, description: "A figure of a local merchant said to reanimate and dance during Hogmanay.", url: "https://www.atlasobscura.com/places/cowanes-hospital" },
  { name: "The Bastion & Thieves Pot", lat: 56.11772, lng: -3.935439, description: "16th-century capital punishment relic hidden in a modern shopping center.", url: "https://www.atlasobscura.com/places/the-bastion-thieves-pot" },
  { name: "The Star Pyramid", lat: 56.122076, lng: -3.945413, description: "Pyramid dedicated to those who suffered martyrdom for civil and religious liberty.", url: "https://www.atlasobscura.com/places/the-star-pyramid" },
  { name: "The World's Oldest Football", lat: 56.11892, lng: -3.946292, description: "16th-century sporting equipment displayed in a local museum.", url: "https://www.atlasobscura.com/places/the-worlds-oldest-football" },
  { name: "Beheading Stone", lat: 56.125617, lng: -3.94507, description: "Rock believed to have served as a chopping block for public executions.", url: "https://www.atlasobscura.com/places/beheading-stone" },
  { name: "Ben Gunn's Cave", lat: 56.167178, lng: -3.952136, description: "Scottish cave that inspired Treasure Island, marked with a carved bench.", url: "https://www.atlasobscura.com/places/ben-gunn-cave-darn-walk-treasure-island" },
  { name: "Leighton Library", lat: 56.188197, lng: -3.964344, description: "Scotland's oldest library, built from church remains.", url: "https://www.atlasobscura.com/places/leighton-library" },
  { name: "The King's Knot", lat: 56.120147, lng: -3.949458, description: "Formal gardens designed to be admired from Stirling Castle's vantage point.", url: "https://www.atlasobscura.com/places/the-kings-knot" },
  { name: "Torwood Blue Pool", lat: 56.042759, lng: -3.864397, description: "Small brick pond whose mystery eluded investigators.", url: "https://www.atlasobscura.com/places/torwood-blue-pool" },

  // === Perth & Central ===
  { name: "Smeaton's Bridge", lat: 56.398951, lng: -3.425652, description: "Bricks indicate the various flood levels this crossing has survived over centuries.", url: "https://www.atlasobscura.com/places/smeatons-bridge" },
  { name: "North Inch", lat: 56.403574, lng: -3.431349, description: "In 1396, two feuding Scottish clans faced off in a bloody battle in this park.", url: "https://www.atlasobscura.com/places/north-inch-park" },
  { name: "Abernethy Round Tower", lat: 56.33292, lng: -3.311763, description: "One of two Irish-style round towers in Scotland with mysterious origins.", url: "https://www.atlasobscura.com/places/abernethy-round-tower" },
  { name: "Lindores Abbey Distillery", lat: 56.352457, lng: -3.224191, description: "One of the youngest whisky distilleries may also be Scotland's oldest.", url: "https://www.atlasobscura.com/places/lindores-abbey-distillery-scotland" },
  { name: "Maggie Wall's Memorial", lat: 56.308821, lng: -3.608142, description: "A mysterious monument where a woman who records say never existed was burnt for being a witch.", url: "https://www.atlasobscura.com/places/monument-for-a-witch-called-maggie-wall" },
  { name: "Meikleour Beech Hedges", lat: 56.5335, lng: -3.3643, description: "Guinness Record holder for the largest hedge in the world.", url: "https://www.atlasobscura.com/places/meikleour-beech-hedges" },
  { name: "Bunnet Stane", lat: 56.249314, lng: -3.308998, description: "This unusual rock looks like a giant, otherworldly mushroom sprouting atop a cave.", url: "https://www.atlasobscura.com/places/bunnet-stane" },
  { name: "Beatrix Potter Garden", lat: 56.558006, lng: -3.577072, description: "This Birnam garden honors the legacy of children's book author Beatrix Potter.", url: "https://www.atlasobscura.com/places/beatrix-potter-garden" },
  { name: "Birnam Oak and Sycamore", lat: 56.55978, lng: -3.579287, description: "Macbeth's infamous 'Great Birnam Wood.'", url: "https://www.atlasobscura.com/places/birnam-oak-and-sycamore" },
  { name: "Ossian's Hall of Mirrors", lat: 56.557371, lng: -3.614808, description: "Described by William Wordsworth as a 'World of Wonder.'", url: "https://www.atlasobscura.com/places/ossians-hall-of-mirrors" },
  { name: "Library of Innerpeffray", lat: 56.350772, lng: -3.783971, description: "Scotland's first free lending library.", url: "https://www.atlasobscura.com/places/library-of-innerpeffray" },
  { name: "Rumbling Bridge", lat: 56.178799, lng: -3.585195, description: "This unusual double arched bridge runs over a picturesque Scottish glen.", url: "https://www.atlasobscura.com/places/rumbling-bridge" },
  { name: "Towser", lat: 56.389157, lng: -3.853087, description: "A sculpture commemorating the 'world's best mouser' in Scotland's longest-running distillery.", url: "https://www.atlasobscura.com/places/towser" },
  { name: "Pitlochry Fish Ladder", lat: 56.698949, lng: -3.740175, description: "Watch salmon leap their way upstream through a series of pools.", url: "https://www.atlasobscura.com/places/pitlochry-fish-ladder" },
  { name: "The Fortingall Yew", lat: 56.598204, lng: -4.050994, description: "One of the oldest living things in Europe, estimated at 2,000-5,000 years old.", url: "https://www.atlasobscura.com/places/the-fortingall-yew" },
  { name: "Earthquake House", lat: 56.371924, lng: -4.000854, description: "A tiny building housing instruments that detect seismic activity.", url: "https://www.atlasobscura.com/places/earthquake-house" },
  { name: "Falls of Dochart", lat: 56.462449, lng: -4.320599, description: "Scenic rapids flowing through the village of Killin.", url: "https://www.atlasobscura.com/places/falls-of-dochart" },
  { name: "Falls of Leny", lat: 56.251067, lng: -4.273208, description: "A dramatic waterfall near Callander in the Trossachs.", url: "https://www.atlasobscura.com/places/falls-of-leny" },
  { name: "Doune Castle", lat: 56.185199, lng: -4.049946, description: "Famous filming location for Monty Python and the Holy Grail and Outlander.", url: "https://www.atlasobscura.com/places/doune-castle" },

  // === Dundee ===
  { name: "Bruin", lat: 56.461024, lng: -2.968935, description: "Monument depicting a harrowing event involving an escaped polar bear.", url: "https://www.atlasobscura.com/places/statue-of-bruin" },
  { name: "The Howff Cemetery", lat: 56.461449, lng: -2.972804, description: "People leave coins atop an unusual grave marker in one of Scotland's oldest burial grounds.", url: "https://www.atlasobscura.com/places/the-howff-cemetery" },
  { name: "Grissel Jaffray Memorial", lat: 56.463018, lng: -2.968558, description: "Mosaics marking where the last accused witch of Dundee was put to death.", url: "https://www.atlasobscura.com/places/grissel-jaffray-memorial" },
  { name: "West Bell Street Car Park", lat: 56.46331, lng: -2.977478, description: "Reportedly haunted parking structure with alleged links to Jack The Ripper.", url: "https://www.atlasobscura.com/places/bell-street-car-park" },
  { name: "Lemmings Statue", lat: 56.456476, lng: -2.980873, description: "Bronze tribute to the wildly popular video game from the '90s.", url: "https://www.atlasobscura.com/places/lemmings-statue" },
  { name: "Tay Bridge Memorial", lat: 56.44068, lng: -2.941197, description: "Monument dedicated to one of the nation's worst engineering disasters.", url: "https://www.atlasobscura.com/places/tay-bridge-memorial" },

  // === St Andrews & Fife ===
  { name: "Hamish McHamish Statue", lat: 56.339316, lng: -2.7965, description: "Bronze statue honoring a beloved local stray cat.", url: "https://www.atlasobscura.com/places/hamish-mchamish-statue" },
  { name: "Gregory's Meridian Line", lat: 56.339329, lng: -2.794222, description: "Scotland's claim to the prime meridian, laid 200 years before Greenwich.", url: "https://www.atlasobscura.com/places/gregorys-meridian-line" },
  { name: "Dunino Den", lat: 56.288169, lng: -2.744473, description: "Ancient pagan worship site that still attracts people looking for fairies.", url: "https://www.atlasobscura.com/places/dunino-den" },
  { name: "Scotland's Secret Bunker", lat: 56.270546, lng: -2.698528, description: "Nuclear bunker built to shelter politicians in case of nuclear attack.", url: "https://www.atlasobscura.com/places/scotland-s-secret-bunker" },
  { name: "Anstruther Model Solar System", lat: 56.221959, lng: -2.697513, description: "Bronze plates form a true-scale model of the solar system.", url: "https://www.atlasobscura.com/places/anstruther-model-solar-system" },
  { name: "Crail Airfield", lat: 56.270811, lng: -2.604876, description: "Soviet intelligence had a keen interest in the Cold War linguistic school here.", url: "https://www.atlasobscura.com/places/crail-raceway" },

  // === Aberdeen & Northeast ===
  { name: "Russell Head", lat: 57.148573, lng: -2.097848, description: "This effigy was crafted to annoy a neighbor after a dispute over a foul smell.", url: "https://www.atlasobscura.com/places/russell-head" },
  { name: "Kelly's Cats", lat: 57.145764, lng: -2.101047, description: "A dozen cast iron leopards stand guard along Aberdeen's Union Bridge.", url: "https://www.atlasobscura.com/places/kellys-cats" },
  { name: "Brig o' Balgownie", lat: 57.1774, lng: -2.096804, description: "Scotland's oldest medieval bridge.", url: "https://www.atlasobscura.com/places/brig-o-balgownie" },
  { name: "Stonehaven Fireball Ceremony", lat: 56.963661, lng: -2.209288, description: "This brilliant display of whirling fireballs celebrates Hogmanay.", url: "https://www.atlasobscura.com/places/stonehaven-fireball-ceremony" },
  { name: "Dunnottar Castle", lat: 56.945688, lng: -2.196242, description: "The ruins of this gorgeous clifftop castle look like something from a fantasy novel.", url: "https://www.atlasobscura.com/places/dunnottar-castle-2" },
  { name: "New Slains Castle Ruins", lat: 57.415209, lng: -1.83243, description: "Remains of a grand castle that may have inspired Bram Stoker's Dracula.", url: "https://www.atlasobscura.com/places/new-slains-castle-ruins" },
  { name: "Aikey Brae Stone Circle", lat: 57.51398, lng: -2.070435, description: "The most original, complete, and unimproved circle in Aberdeenshire.", url: "https://www.atlasobscura.com/places/aikey-brae-stone-circle" },
  { name: "East Mathers Lime Kiln", lat: 56.787561, lng: -2.35811, description: "18th-century industrial site repurposed in WWII along the wild North Sea coast.", url: "https://www.atlasobscura.com/places/east-mathers-lime-kiln" },
  { name: "Strichen Stone Circle", lat: 57.5804, lng: -2.107492, description: "This ancient monument has been disassembled and put back together at least twice.", url: "https://www.atlasobscura.com/places/strichen-stone-circle" },
  { name: "Burn O'Vat", lat: 57.084789, lng: -2.943708, description: "A glacial pothole was once a hideout for a notorious Scottish outlaw.", url: "https://www.atlasobscura.com/places/burn-ovat" },
  { name: "Memsie Round Cairn", lat: 57.648363, lng: -2.040968, description: "The sole surviving large cairn in an area once littered with burial monuments.", url: "https://www.atlasobscura.com/places/memsie-round-cairn" },
  { name: "St Drostan's Well", lat: 57.670993, lng: -2.191281, description: "Believed to be the site where St. Drostan performed baptisms.", url: "https://www.atlasobscura.com/places/st-drostans-well" },

  // === Cairngorms National Park ===
  { name: "CairnGorm Mountain Railway", lat: 57.134933, lng: -3.679681, description: "Scotland's only funicular railway is also the United Kingdom's highest.", url: "https://www.atlasobscura.com/places/cairngorm-mountain-railway" },
  { name: "Cairngorm Reindeer Centre", lat: 57.16696, lng: -3.691234, description: "Britain's only herd of free-ranging reindeer.", url: "https://www.atlasobscura.com/places/the-cairngorm-reindeer-centre-highland-scotland" },
  { name: "Frank Bruce Sculpture Trail", lat: 57.118312, lng: -3.902216, description: "These skilfully executed, poignant works of art dot a verdant Scottish dell.", url: "https://www.atlasobscura.com/places/frank-bruce-sculpture-trail" },
  { name: "Ruthven Barracks", lat: 57.072222, lng: -4.039444, description: "These ruins witnessed the final gathering of the failed Jacobite Rebellion.", url: "https://www.atlasobscura.com/places/ruthven-barracks" },
  { name: "Corgarff Castle", lat: 57.163063, lng: -3.234234, description: "This Scottish castle has witnessed clan rivalries, Jacobite uprisings, whisky smuggling, and more.", url: "https://www.atlasobscura.com/places/corgarff-castle" },
  { name: "The Geographic Center of Scotland", lat: 57.021, lng: -4.177, description: "A cross marks the spot in a small Scottish village that claims to be the exact center of the country.", url: "https://www.atlasobscura.com/places/the-geographic-center-of-scotland-highland-scotland" },
  { name: "Garbh Allt Falls Bridge", lat: 56.984879, lng: -3.329413, description: "More than a century old, this cast iron bridge on the Balmoral Estate leads to nowhere.", url: "https://www.atlasobscura.com/places/garbh-allt-falls-bridge" },
  { name: "Croft Moraig Stone Circle", lat: 56.601747, lng: -3.960312, description: "This Neolithic stone circle is the most complete of its kind in Scotland.", url: "https://www.atlasobscura.com/places/croft-moraig-stone-circle" },
  { name: "Tummel Bridge Hydro Power Station", lat: 56.706441, lng: -4.021233, description: "One of Scotland's earliest hydroelectric power stations.", url: "https://www.atlasobscura.com/places/tummel-bridge-hydro-power-station" },
  { name: "Tomphubil Lime-Kiln", lat: 56.666494, lng: -3.995703, description: "A small, former industrial site overlooking Loch Kinardochy.", url: "https://www.atlasobscura.com/places/tomphubil-lime-kiln" },

  // === Inverness & Highlands ===
  { name: "Old High Church Kirkyard", lat: 57.479942, lng: -4.228654, description: "The oldest church in Inverness witnessed brutal executions of Scottish soldiers.", url: "https://www.atlasobscura.com/places/old-high-church-kirkyard" },
  { name: "Ship Space", lat: 57.485091, lng: -4.251745, description: "A Scottish man's backyard recreation where the Titanic sails again.", url: "https://www.atlasobscura.com/places/titanic-inverness-maritime-museum" },
  { name: "Cumberland's Stone", lat: 57.480479, lng: -4.086929, description: "Rock that witnessed the final pitched battle fought on British soil.", url: "https://www.atlasobscura.com/places/cumberlands-stone" },
  { name: "Clootie Well", lat: 57.552697, lng: -4.273611, description: "An enduring pagan tradition involving cloth offerings on trees.", url: "https://www.atlasobscura.com/places/clootie-well" },
  { name: "Clava Cairns", lat: 57.473498, lng: -4.073168, description: "Ancient burial grounds spanning approximately 1,000 years.", url: "https://www.atlasobscura.com/places/clava-cairns-2" },
  { name: "Wych Elm of Beauly Priory", lat: 57.484613, lng: -4.457783, description: "Europe's oldest elm tree, standing for 800 years.", url: "https://www.atlasobscura.com/places/wych-elm-of-beauly-priory" },
  { name: "The Fairy Glen (Rosemarkie)", lat: 57.599053, lng: -4.13219, description: "A nature walk leading to the origins of a local legend.", url: "https://www.atlasobscura.com/places/the-fairy-glen-rosemarkie" },
  { name: "Cawdor Castle", lat: 57.524275, lng: -3.926562, description: "Historic castle whose location was inspired by a donkey.", url: "https://www.atlasobscura.com/places/cawdor-castle" },
  { name: "Rait Castle", lat: 57.549439, lng: -3.849817, description: "A 13th-century castle ruin at the end of a farm track.", url: "https://www.atlasobscura.com/places/rait-castle" },
  { name: "Oil Rig Graveyard", lat: 57.687738, lng: -4.11392, description: "Where Scotland's oil industry rigs are left to rust.", url: "https://www.atlasobscura.com/places/oil-rig-graveyard" },
  { name: "Dulsie Bridge", lat: 57.45073, lng: -3.781432, description: "An outstanding 18th-century bridge.", url: "https://www.atlasobscura.com/places/dulsie-bridge" },
  { name: "Boleskine House", lat: 57.265323, lng: -4.474721, description: "A manor steeped in tales of unexplained fires, mysticism, and peculiar history.", url: "https://www.atlasobscura.com/places/boleskine-house" },
  { name: "Inchindown Oil Tanks", lat: 57.739723, lng: -4.201664, description: "Abandoned depot hosting the world's longest echo in a manmade structure.", url: "https://www.atlasobscura.com/places/inchindown-oil-tanks" },
  { name: "Old Packhorse Bridge", lat: 57.283809, lng: -3.81575, description: "Built to facilitate funeral processions across the River Dulnain.", url: "https://www.atlasobscura.com/places/old-packhorse-bridge" },
  { name: "Clach a' Charridh", lat: 57.747547, lng: -3.924567, description: "An intricately carved Pictish stone preserved within protective glass.", url: "https://www.atlasobscura.com/places/clach-a-charridh-scotland" },

  // === Fort William & Glen Coe ===
  { name: "Neptune's Staircase", lat: 56.846058, lng: -5.095239, description: "The longest staircase lock in Britain.", url: "https://www.atlasobscura.com/places/neptunes-staircase-scotland" },
  { name: "Ben Nevis", lat: 56.796857, lng: -5.00355, description: "The highest peak in the UK has a history of physics, specters, and strange pilgrimages.", url: "https://www.atlasobscura.com/places/ben-nevis" },
  { name: "Massacre of Glencoe Monument", lat: 56.68242, lng: -5.09511, description: "A solemn memorial in a majestic setting honoring a 1692 tragedy.", url: "https://www.atlasobscura.com/places/massacre-of-glencoe-monument" },
  { name: "Ralston Cairn", lat: 56.664142, lng: -4.967735, description: "A lonely memorial atop a wind-swept crag to a beloved hiker.", url: "https://www.atlasobscura.com/places/ralston-cairn" },
  { name: "The Meeting of Three Waters", lat: 56.662507, lng: -4.966419, description: "Featured in Monty Python and the Holy Grail as the Bridge of Death.", url: "https://www.atlasobscura.com/places/the-meeting-of-three-waters" },
  { name: "Grey Mare's Tail Waterfall", lat: 56.7190261, lng: -4.9633921, description: "A dramatic 300-foot waterfall cascading down the hillside near Kinlochleven.", url: "" },
  { name: "Falls of Glencoe", lat: 56.6622393, lng: -4.9660004, description: "Scenic waterfall in Glencoe village, easily accessible from the main road.", url: "" },
  { name: "Glenfinnan Viaduct", lat: 56.876323, lng: -5.431851, description: "An impressive concrete viaduct, now famous as the Harry Potter bridge.", url: "https://www.atlasobscura.com/places/glenfinnan-viaduct" },
  { name: "The Leaning Tower of Glenfinnan", lat: 56.86908, lng: -5.439247, description: "A Scottish monument that is slightly off-kilter upon close inspection.", url: "https://www.atlasobscura.com/places/the-leaning-tower-of-glenfinnan-glenfinnan-scotland" },
  { name: "Glengarry Viewpoint", lat: 57.08186, lng: -4.953083, description: "From this viewpoint, the loch appears to take the shape of mainland Scotland.", url: "https://www.atlasobscura.com/places/glengarry-viewpoint" },
  { name: "Well of the Seven Heads", lat: 57.052164, lng: -4.797026, description: "A macabre monument atop an ancient well commemorating a brutal clan episode.", url: "https://www.atlasobscura.com/places/well-of-the-seven-heads" },
  { name: "Willie MacRae Memorial", lat: 57.116286, lng: -4.981877, description: "A solitary cairn marking a mysterious death that remains controversial.", url: "https://www.atlasobscura.com/places/willie-macrae-memorial" },
  { name: "The Bridge of Oich", lat: 57.093366, lng: -4.745255, description: "A double cantilever bridge designed to prevent flood damage.", url: "https://www.atlasobscura.com/places/the-bridge-of-oich" },
  { name: "The Old Forge", lat: 57.037387, lng: -5.6827, description: "A remote pub in the middle of nowhere that continues to operate.", url: "https://www.atlasobscura.com/places/the-old-forge-knoydart-scotland" },

  // === Staffa & Mull ===
  { name: "Fingal's Cave", lat: 56.43135, lng: -6.341347, description: "This astonishingly geometric cave has inspired everyone from Jules Verne to Pink Floyd.", url: "https://www.atlasobscura.com/places/fingal-s-cave" },
  { name: "The Fossil Tree and Burg", lat: 56.371218, lng: -6.208717, description: "A 50-million-year-old fossil tree hidden in coastal cliffs on the Ardmeanach peninsula, Isle of Mull.", url: "https://www.atlasobscura.com/places/burg" },
  { name: "Iona Abbey", lat: 56.335091, lng: -6.391796, description: "A small island abbey is the final resting place of many medieval Scottish monarchs, including the real Macbeth.", url: "https://www.atlasobscura.com/places/iona-abbey" },
  { name: "Massacre Cave", lat: 56.893676, lng: -6.153307, description: "This cramped crevasse saw the entire population of its island suffocated inside its depths.", url: "https://www.atlasobscura.com/places/massacre-cave" },

  // === Oban & Argyll ===
  { name: "McCaig's Tower", lat: 56.415658, lng: -5.469169, description: "An unfinished tower resembling Rome's Colosseum dominating Oban's skyline.", url: "https://www.atlasobscura.com/places/mccaig-s-tower" },
  { name: "Clachan Bridge", lat: 56.317721, lng: -5.582851, description: "Known as the 'Bridge Over the Atlantic.'", url: "https://www.atlasobscura.com/places/clachan-bridge-bridge-over-atlantic" },
  { name: "World Stone Skimming Championship", lat: 56.291892, lng: -5.654351, description: "International competitors gather at flooded quarries on a Scottish island.", url: "https://www.atlasobscura.com/places/world-stone-skimming-championship" },
  { name: "Ben Cruachan", lat: 56.428475, lng: -5.12598, description: "One of Scotland's largest mountains, better known for its hollow insides.", url: "https://www.atlasobscura.com/places/ben-cruachan" },
  { name: "Saint Conan's Kirk", lat: 56.39511, lng: -5.053888, description: "An eclectic sanctuary combining multiple architectural styles.", url: "https://www.atlasobscura.com/places/saint-conans-kirk" },
  { name: "Kilchurn Castle", lat: 56.403719, lng: -5.027404, description: "Ruins overlooking a loch that inspired William Wordsworth poetry.", url: "https://www.atlasobscura.com/places/kilchurn-castle" },
  { name: "Kilmartin Glen Prehistoric Monuments", lat: 56.133759, lng: -5.486727, description: "Neolithic monuments in one of the UK's most archaeologically significant landscapes.", url: "https://www.atlasobscura.com/places/kilmartin-glen-prehistoric-monuments" },
  { name: "Corryvreckan Whirlpool", lat: 56.153581, lng: -5.707058, description: "The world's third-largest whirlpool, allegedly created by a witch.", url: "https://www.atlasobscura.com/places/corryvreckan-whirlpool" },
  { name: "Ardchattan Priory", lat: 56.462585, lng: -5.294981, description: "A private home envelops the ruins of this 13th-century priory.", url: "https://www.atlasobscura.com/places/ardchattan-priory" },
  { name: "Dun na Cuaiche Watchtower", lat: 56.245573, lng: -5.067457, description: "18th-century viewing structure overlooking the highlands.", url: "https://www.atlasobscura.com/places/dun-na-cuaiche-watchtower" },
  { name: "Clach Na Criche (The Wishing Stone)", lat: 56.550193, lng: -5.895358, description: "Ancient lava-formed stone that served as a rest stop during funeral processions.", url: "https://www.atlasobscura.com/places/clach-na-criche-the-wishing-stone" },
  { name: "Poltalloch House", lat: 56.111047, lng: -5.517511, description: "Ruins of a 19th-century Scottish Baronial mansion reflecting architectural heritage.", url: "https://www.atlasobscura.com/places/poltalloch-house" },
  { name: "Dunchraigaig Cairn and Baluachraig Rock Art", lat: 56.114715, lng: -5.487041, description: "No other place in Scotland has such a high concentration of prehistoric carved stone surfaces.", url: "https://www.atlasobscura.com/places/dunchraigaig-rock-art-and-cairn" },
  { name: "Ballymeanoch Prehistoric Monuments", lat: 56.111214, lng: -5.485659, description: "This Neolithic-era complex boasts standing stones, a cairn, and the only henge in Western Scotland.", url: "https://www.atlasobscura.com/places/ballymeanoch-prehistoric-monuments" },

  // === Isle of Skye ===
  { name: "Fairy Pools", lat: 57.247305, lng: -6.256485, description: "Natural pools that resemble something from Scottish mythology.", url: "https://www.atlasobscura.com/places/fairy-pools" },
  { name: "Skye Textile Mill", lat: 57.391563, lng: -6.512355, description: "Historic site featuring antique textile equipment in active operation.", url: "https://www.atlasobscura.com/places/skye-textile-mill" },
  { name: "Giant Angus MacAskill Museum", lat: 57.435411, lng: -6.579332, description: "Museum dedicated to the world's tallest true giant.", url: "https://www.atlasobscura.com/places/giant-angus-macaskill-museum" },
  { name: "Spar Cave", lat: 57.140021, lng: -6.070511, description: "Stunning cave with significance in Scottish poetry.", url: "https://www.atlasobscura.com/places/spar-cave" },
  { name: "Calum's Road", lat: 57.443603, lng: -6.030081, description: "One man spent 10 years building this road by hand.", url: "https://www.atlasobscura.com/places/calums-road" },
  { name: "Fairy Flag of Dunvegan Castle", lat: 57.448444, lng: -6.590064, description: "Tattered flag with murky origins and supposed magic powers.", url: "https://www.atlasobscura.com/places/dunvegan-castle-fairy-flag-scotland" },
  { name: "The Old Man of Storr", lat: 57.509264, lng: -6.152534, description: "Ancient rock formation linked to a giant's gravesite legend.", url: "https://www.atlasobscura.com/places/the-old-man-of-storr" },
  { name: "Fairy Glen (Skye)", lat: 57.5826, lng: -6.3253, description: "Dramatic hidden landscape appearing otherworldly.", url: "https://www.atlasobscura.com/places/fairy-glen" },
  { name: "Caisteal Maol", lat: 57.272677, lng: -5.720316, description: "Ruined castle said to be the stronghold of a Viking princess.", url: "https://www.atlasobscura.com/places/caisteal-maol-isle-of-skye-scotland" },
  { name: "Kilt Rock and Mealt Falls", lat: 57.610636, lng: -6.172385, description: "Ancient cliff formations resembling a kilt.", url: "https://www.atlasobscura.com/places/kilt-rock-and-mealt-falls" },
  { name: "Isle of Skye Dinosaur Tracks", lat: 57.63656, lng: -6.20494, description: "Fossilized footprints of prehistoric creatures preserved in stone.", url: "https://www.atlasobscura.com/places/skyes-dinosaur-footprints" },
  { name: "Applecross Pass", lat: 57.418914, lng: -5.708556, description: "Single-track road offering dramatic vistas for adventurous drivers.", url: "https://www.atlasobscura.com/places/applecross-pass" },
  { name: "The Quiraing", lat: 57.643611, lng: -6.265278, description: "Otherworldly terrain historically used to hide cattle from Viking raiders.", url: "https://www.atlasobscura.com/places/the-quiraing" },
  { name: "MV Glenachulish Ferry", lat: 57.227729, lng: -5.665577, description: "The world's last manually operated turntable ferry.", url: "https://www.atlasobscura.com/places/mv-glenachulish" },
  { name: "Kinloch Castle", lat: 57.015406, lng: -6.281487, description: "Once-grand Victorian castle now in declining condition.", url: "https://www.atlasobscura.com/places/kinloch-castle" },
  { name: "The Lookout (Rubha Hunish)", lat: 57.701438, lng: -6.344562, description: "A former coastal watch post turned bothy with unrivaled views.", url: "https://www.atlasobscura.com/places/the-lookout" },
  { name: "Kilmuir Cemetery", lat: 57.661202, lng: -6.360636, description: "Resting place of a heroine of Highlands history alongside unusual graves.", url: "https://www.atlasobscura.com/places/kilmuir-cemetery-scotland" },

  // === Orkney ===
  { name: "Cuween Hill Cairn", lat: 58.997117, lng: -3.107778, description: "Enter the world under the hill at this ancient burial chamber.", url: "https://www.atlasobscura.com/places/cuween-hill-cairn-2" },
  { name: "Maeshowe", lat: 58.995647, lng: -3.188284, description: "Ancient Neolithic chambered cairn with Viking runic graffiti.", url: "https://www.atlasobscura.com/places/maeshowe" },
  { name: "The Stones of Stenness", lat: 58.99398, lng: -3.20775, description: "Possibly the oldest of Britain's ancient henges.", url: "https://www.atlasobscura.com/places/the-stones-of-stenness-orkney-scotland" },
  { name: "Ness of Brodgar", lat: 58.997027, lng: -3.214885, description: "Neolithic settlement that surprised archaeologists.", url: "https://www.atlasobscura.com/places/ness-of-brodgar" },
  { name: "Ring of Brodgar", lat: 59.002, lng: -3.2287, description: "Ancient stone circle with unknown age but striking views.", url: "https://www.atlasobscura.com/places/ring-of-brodgar" },
  { name: "Kirkwall Ba", lat: 58.981571, lng: -2.960599, description: "Twice-yearly medieval mob football game.", url: "https://www.atlasobscura.com/places/kirkwall-ba" },
  { name: "The Italian Chapel", lat: 58.88968, lng: -2.89005, description: "WWII chapel constructed by Italian prisoners of war.", url: "https://www.atlasobscura.com/places/the-italian-chapel-orkney-scotland" },
  { name: "Skara Brae", lat: 59.0486, lng: -3.3431, description: "Remarkable Neolithic settlement on Scotland's Orkney Islands.", url: "https://www.atlasobscura.com/places/skara-brae" },
  { name: "Dwarfie Stane", lat: 58.884444, lng: -3.314333, description: "Megalithic tomb with legends of giants and dwarves.", url: "https://www.atlasobscura.com/places/dwarfie-stane" },
  { name: "Old Man of Hoy", lat: 58.88585, lng: -3.428237, description: "Red sandstone monolith rising from the sea.", url: "https://www.atlasobscura.com/places/old-man-of-hoy" },
  { name: "Brough of Birsay", lat: 59.135751, lng: -3.336147, description: "Tiny island with 9th-century Viking ruins, accessible only at low tide.", url: "https://www.atlasobscura.com/places/brough-of-birsay" },
  { name: "Tomb of the Eagles", lat: 58.74, lng: -2.922, description: "Burial tomb that once held hundreds of ancient eagle bones.", url: "https://www.atlasobscura.com/places/tomb-of-the-eagles" },

  // === Far North & Flow Country ===
  { name: "John o' Groats Marker", lat: 58.643976, lng: -3.069947, description: "Sign marking one endpoint of mainland Britain's longest overland route.", url: "https://www.atlasobscura.com/places/john-ogroats" },
  { name: "Dunnet Head Lighthouse", lat: 58.671414, lng: -3.376111, description: "The most northern point on mainland Great Britain.", url: "https://www.atlasobscura.com/places/dunnet-head" },
  { name: "Ebenezer Place", lat: 58.441208, lng: -3.094072, description: "World's shortest street, created by an awkwardly positioned hotel.", url: "https://www.atlasobscura.com/places/ebenezer-place" },
  { name: "Hermit's Castle", lat: 58.168467, lng: -5.314542, description: "Believed to be the smallest castle in Europe.", url: "https://www.atlasobscura.com/places/hermits-castle" },
  { name: "Hill O' Many Stanes", lat: 58.328557, lng: -3.205036, description: "A collection of short standing stones covers this hillside.", url: "https://www.atlasobscura.com/places/hill-o-many-stanes" },
  { name: "Abandoned Badbea", lat: 58.159, lng: -3.551, description: "An abandoned village where the ruined foundations cling to a cliff.", url: "https://www.atlasobscura.com/places/abandoned-badbea" },

  // === Outer Hebrides / Lewis & Harris ===
  { name: "Callanish Stones", lat: 58.19755, lng: -6.745148, description: "Mysterious megaliths that have enchanted visitors for thousands of years.", url: "https://www.atlasobscura.com/places/callanish-stones" },
  { name: "Dun Carloway", lat: 58.269542, lng: -6.794019, description: "A magnificent, iconic stone tower in the Scottish Highlands.", url: "https://www.atlasobscura.com/places/dun-carloway" },
  { name: "Gearrannan Blackhouse Village", lat: 58.296593, lng: -6.793042, description: "Spend the night in this formerly abandoned traditional Scottish village.", url: "https://www.atlasobscura.com/places/gearrannan-blackhouse-village" },
  { name: "Rubha Robhanais (Butt of Lewis)", lat: 58.515483, lng: -6.261606, description: "Red-brick beacon on the windiest site in the UK.", url: "https://www.atlasobscura.com/places/rubha-robhanais-butt-lewis-lighthouse" },
  { name: "Iolaire Memorial", lat: 58.18893, lng: -6.348861, description: "Memorial to a boating accident bringing troops home from WWI.", url: "https://www.atlasobscura.com/places/iolaire-memorial" },
  { name: "The Bridge to Nowhere", lat: 58.370263, lng: -6.223502, description: "A failed infrastructure project.", url: "https://www.atlasobscura.com/places/garry-bridge-the-bridge-to-nowhere" },
  { name: "Whale Bone Arch", lat: 58.334041, lng: -6.62865, description: "A whale's jawbone and a malfunctioning harpoon welcome you to Bragar.", url: "https://www.atlasobscura.com/places/whale-bone-arch" },
  { name: "Clach an Truseil", lat: 58.393407, lng: -6.492906, description: "Scotland's tallest standing stone, 5,000 years old.", url: "https://www.atlasobscura.com/places/clach-an-truseil" },
  { name: "The Scarista Bus", lat: 57.797041, lng: -7.066276, description: "A mysterious weather-beaten bus on the coast of Harris.", url: "https://www.atlasobscura.com/places/scarista-abandoned-bus" },
  { name: "Macleod's Stone", lat: 57.865564, lng: -6.993011, description: "Standing stone with a backdrop of some of the UK's best-rated beaches.", url: "https://www.atlasobscura.com/places/macleods-stone" },
  { name: "Hercules the Bear Memorial", lat: 57.564684, lng: -7.288494, description: "Memorial to an acting bear whose escape caused a sensation.", url: "https://www.atlasobscura.com/places/hercules" },
  { name: "Scolpaig Tower", lat: 57.646108, lng: -7.481808, description: "A Georgian-era folly designed to resemble a castle.", url: "https://www.atlasobscura.com/places/scolpaig-tower" },
  { name: "Teampull na Trionaid", lat: 57.520314, lng: -7.320107, description: "Medieval seminary ruins considered Scotland's oldest university site.", url: "https://www.atlasobscura.com/places/teampull-na-trionaid" },
  { name: "Time and Tide Bell (Bosta Beach)", lat: 58.258813, lng: -6.882188, description: "Sculpture making a statement about sea-level rise.", url: "https://www.atlasobscura.com/places/time-and-tide-bell-at-bosta-beach" },

  // === Shetland ===
  { name: "Up Helly Aa", lat: 60.152987, lng: -1.149293, description: "Hundreds of torch-carriers burn a Viking longboat in this Shetland celebration.", url: "https://www.atlasobscura.com/places/up-helly-aa" },
  { name: "Broch of Mousa", lat: 59.995271, lng: -1.182071, description: "A remarkably well preserved Iron Age tower.", url: "https://www.atlasobscura.com/places/broch-of-mousa" },
  { name: "Bobby's Bus Shelter", lat: 60.765395, lng: -0.834831, description: "This bus shelter squeezes in a couch, desk, art, and an old television.", url: "https://www.atlasobscura.com/places/bobbys-bus-shelter" },
  { name: "Shetland Cake Fridges", lat: 60.302034, lng: -1.346384, description: "Across the islands, baked goods are for sale 24/7 via honesty boxes.", url: "https://www.atlasobscura.com/places/shetland-cake-fridges-and-honesty-boxes" },
  { name: "The Shetland Bus Memorial", lat: 60.137473, lng: -1.27955, description: "Celebrates the British-Norwegian resistance movement during WWII.", url: "https://www.atlasobscura.com/places/the-shetland-bus-memorial" },
  { name: "The Hjaltadans Stone Circle", lat: 60.616667, lng: -0.866667, description: "On a remote island, a fiddler and his wife were turned to stone.", url: "https://www.atlasobscura.com/places/the-hjaltadans-stone-circle" },
  { name: "The Gloup Disaster Memorial", lat: 60.720812, lng: -1.073438, description: "Memorial to a 19th-century fishing disaster.", url: "https://www.atlasobscura.com/places/the-gloup-disaster-memorial" },
  { name: "Ayres of Swinister", lat: 60.433562, lng: -1.190563, description: "This geographic feature might be unique in the world.", url: "https://www.atlasobscura.com/places/ayres-of-swinister" },
  { name: "The Dutchman's Leap", lat: 60.145858, lng: -1.138642, description: "Legend says a Dutch fisherman lost control of his pony and tumbled from this cliff.", url: "https://www.atlasobscura.com/places/the-dutchmans-leap" },

  // === Scottish Borders ===
  { name: "Hume Castle", lat: 55.665169, lng: -2.470937, description: "From fortification to folly, this hilltop structure has changed over 800 years.", url: "https://www.atlasobscura.com/places/hume-castle" },
  { name: "Scott's View", lat: 55.600474, lng: -2.646663, description: "Picturesque panorama cherished by Sir Walter Scott.", url: "https://www.atlasobscura.com/places/scotts-view" },
  { name: "The Sir William Wallace Statue", lat: 55.586162, lng: -2.649481, description: "Massive 30-foot statue of the famed Scottish knight.", url: "https://www.atlasobscura.com/places/sir-william-wallace-statue" },
  { name: "The Cement Menagerie", lat: 55.629535, lng: -2.176841, description: "Whimsical garden of outsider art displaying a father's love for his son.", url: "https://www.atlasobscura.com/places/the-cement-menagerie" },
  { name: "The Rhymer's Stone", lat: 55.594692, lng: -2.695759, description: "Where a Scottish poet allegedly encountered the Queen of the Fairies.", url: "https://www.atlasobscura.com/places/the-rhymer-stone" },
  { name: "The Capon Tree", lat: 55.462409, lng: -2.553605, description: "1,000-year-old oak, surviving relic of the ancient Jedforest.", url: "https://www.atlasobscura.com/places/the-capon-tree" },
  { name: "Robert the Bruce's Heart", lat: 55.599081, lng: -2.717978, description: "Heart of a Scottish legend with a centuries-long journey to its final resting place.", url: "https://www.atlasobscura.com/places/robert-the-bruces-heart" },
  { name: "Wojtek the Soldier Bear", lat: 55.777953, lng: -2.344132, description: "Beloved war-time celebrity who spent time in the area.", url: "https://www.atlasobscura.com/places/wojtek-the-bear-in-the-scottish-borders" },
  { name: "Abbotsford House", lat: 55.599347, lng: -2.782233, description: "Scottish manor reflecting Sir Walter Scott's life and legacy.", url: "https://www.atlasobscura.com/places/abbotsford-house" },
  { name: "Duddo Five Stones", lat: 55.686807, lng: -2.112038, description: "Ancient monument where more than five stones once stood.", url: "https://www.atlasobscura.com/places/duddo-five-stones" },
  { name: "Panel 36 (Rosslyn Chapel)", lat: 55.617316, lng: -2.809655, description: "Only replaced panel of the Great Tapestry of Scotland after original theft.", url: "https://www.atlasobscura.com/places/panel-36-rosslyn-chapel" },
  { name: "Coldstream Marriage House", lat: 55.654956, lng: -2.242595, description: "Scottish tollhouse used for clandestine marriages.", url: "https://www.atlasobscura.com/places/coldstream-marriage-house" },
  { name: "Monteath Mausoleum", lat: 55.533618, lng: -2.615115, description: "Beautiful Victorian-era mausoleum designed for a single occupant.", url: "https://www.atlasobscura.com/places/monteath-mausoleum" },

  // === Dumfries & Galloway ===
  { name: "Moat Brae", lat: 55.07147, lng: -3.613208, description: "J.M. Barrie credited it for helping inspire the story of Peter Pan.", url: "https://www.atlasobscura.com/places/moat-brae" },
  { name: "Dumfries Camera Obscura", lat: 55.065086, lng: -3.614266, description: "The oldest working camera obscura in the world.", url: "https://www.atlasobscura.com/places/dumfries-camera-obscura" },
  { name: "Garden of Cosmic Speculation", lat: 55.130149, lng: -3.666329, description: "A 30-acre garden inspired by modern physics.", url: "https://www.atlasobscura.com/places/garden-of-cosmic-speculation" },
  { name: "The Ruthwell Cross", lat: 55.000304, lng: -3.407548, description: "Anglo-Saxon cross with possibly the oldest written work of English literature.", url: "https://www.atlasobscura.com/places/the-ruthwell-cross-dumfries-and-galloway-scotland" },
  { name: "Lockerbie Memorial Garden", lat: 55.115456, lng: -3.36109, description: "Remembrance of local victims of the 1988 bombing.", url: "https://www.atlasobscura.com/places/lockerbie-memorial-garden" },
  { name: "The Devil's Porridge", lat: 54.985297, lng: -3.169905, description: "Story of HM Factory Gretna and the munitions girls who mixed deadly chemicals.", url: "https://www.atlasobscura.com/places/the-devils-porridge" },
  { name: "The Moffat Ram", lat: 55.333697, lng: -3.444815, description: "It has nae lugs!", url: "https://www.atlasobscura.com/places/the-moffat-ram-moffat-scotland" },
  { name: "Buittle Castle", lat: 54.935539, lng: -3.846095, description: "Former seat of power for the Balliol dynasty.", url: "https://www.atlasobscura.com/places/buittle-castle" },
  { name: "Galloway Kite Trail", lat: 54.940415, lng: -3.931414, description: "A tour to spot Scotland's once-vanished birds of prey.", url: "https://www.atlasobscura.com/places/galloway-kite-trail" },
  { name: "Loupin' Stanes and Girdle Stanes", lat: 55.258499, lng: -3.170758, description: "A pair of stone circles on the bank of the River Esk.", url: "https://www.atlasobscura.com/places/loupin-stanes-and-girdle-stanes" },

  // === Southwest / Stranraer / Galloway ===
  { name: "Dunskey Castle", lat: 54.835429, lng: -5.109748, description: "Ruins of a 12th-century seaside castle.", url: "https://www.atlasobscura.com/places/dunskey-castle" },
  { name: "Kirkmadrine Stones", lat: 54.793534, lng: -4.987818, description: "Among the oldest Christian memorials in Scotland, dating to the 500s.", url: "https://www.atlasobscura.com/places/kirkmadrine-stones" },
  { name: "Port Logan Fish Pond", lat: 54.730822, lng: -4.964676, description: "The oldest natural aquarium in the United Kingdom.", url: "https://www.atlasobscura.com/places/port-logan-fish-pond" },
  { name: "Sawney Bean's Cave", lat: 55.146141, lng: -4.984543, description: "Legend says this cave housed a 16th-century cannibal and his family of 48.", url: "https://www.atlasobscura.com/places/sawney-beans-cave" },
  { name: "Torhouse Stone Circle", lat: 54.876969, lng: -4.522521, description: "19 boulders have stood in the Bladnoch Valley for some 4,000 years.", url: "https://www.atlasobscura.com/places/torhouse-stone-circle" },
  { name: "The Open Book", lat: 54.867295, lng: -4.444579, description: "A holiday rental that lets you live out your bookselling dreams.", url: "https://www.atlasobscura.com/places/open-book-hotel" },
  { name: "Martyrs' Tomb Glen Trool", lat: 55.077647, lng: -4.51238, description: "A stone tomb marks where six men were killed at a Covenanter service.", url: "https://www.atlasobscura.com/places/martyrs-tomb-glen-trool" },

  // === Ayrshire ===
  { name: "Electric Brae Gravity Hill", lat: 55.374498, lng: -4.759956, description: "An optical illusion once believed to be an electrical phenomenon.", url: "https://www.atlasobscura.com/places/electric-brae" },
  { name: "Dunure Castle", lat: 55.404982, lng: -4.761694, description: "Ruins of a castle that saw a number of gruesome events.", url: "https://www.atlasobscura.com/places/dunure-castle" },
  { name: "Dunaskin Ironworks", lat: 55.34556, lng: -4.46533, description: "Wonderfully preserved Victorian factory with a steam-powered engine house.", url: "https://www.atlasobscura.com/places/dunaskin-ironworks-brickworks" },
  { name: "Scottish Dark Sky Observatory", lat: 55.291121, lng: -4.404795, description: "Observatory within Europe's first dark sky park.", url: "https://www.atlasobscura.com/places/scottish-dark-sky-observatory" },
  { name: "Whitelee Wind Farm", lat: 55.712253, lng: -4.342883, description: "The biggest onshore wind farm in the United Kingdom.", url: "https://www.atlasobscura.com/places/whitelee-wind-farm" },
  { name: "Laigh Milton Viaduct", lat: 55.5988, lng: -4.56684, description: "May be the oldest surviving railway viaduct in the world.", url: "https://www.atlasobscura.com/places/laigh-milton-viaduct" },
  { name: "Dalquharran Castle", lat: 55.283209, lng: -4.72491, description: "Ruins blending Gothic and Renaissance architectural styles.", url: "https://www.atlasobscura.com/places/dalquharran-castle" },
  { name: "Eglinton Castle", lat: 55.644469, lng: -4.666424, description: "Ruins of a castle that hosted a tournament with 100,000 attendees.", url: "https://www.atlasobscura.com/places/eglinton-castle-scotland" },
]

export default ATLAS_OBSCURA_PLACES
