// October climate averages for Scottish council areas
// Data compiled from Met Office and historical records
const CLIMATE_DATA = {
  "Aberdeen City": { avgHighF: 54, avgLowF: 43, rainfallIn: 3.1, daylightHrs: 10.5 },
  "Aberdeenshire": { avgHighF: 52, avgLowF: 41, rainfallIn: 3.7, daylightHrs: 10.5 },
  "Angus": { avgHighF: 54, avgLowF: 41, rainfallIn: 3.3, daylightHrs: 10.5 },
  "Argyll and Bute": { avgHighF: 54, avgLowF: 45, rainfallIn: 6.7, daylightHrs: 10.5 },
  "City of Edinburgh": { avgHighF: 55, avgLowF: 45, rainfallIn: 2.6, daylightHrs: 10.5 },
  "Clackmannanshire": { avgHighF: 54, avgLowF: 43, rainfallIn: 3.5, daylightHrs: 10.5 },
  "Dumfries and Galloway": { avgHighF: 55, avgLowF: 45, rainfallIn: 4.7, daylightHrs: 10.5 },
  "Dundee City": { avgHighF: 54, avgLowF: 43, rainfallIn: 2.8, daylightHrs: 10.5 },
  "East Ayrshire": { avgHighF: 54, avgLowF: 43, rainfallIn: 5.1, daylightHrs: 10.5 },
  "East Dunbartonshire": { avgHighF: 54, avgLowF: 43, rainfallIn: 4.7, daylightHrs: 10.5 },
  "East Lothian": { avgHighF: 55, avgLowF: 45, rainfallIn: 2.4, daylightHrs: 10.5 },
  "East Renfrewshire": { avgHighF: 54, avgLowF: 43, rainfallIn: 5.1, daylightHrs: 10.5 },
  "Eilean Siar": { avgHighF: 54, avgLowF: 46, rainfallIn: 5.5, daylightHrs: 10.5 },
  "Falkirk": { avgHighF: 54, avgLowF: 43, rainfallIn: 3.3, daylightHrs: 10.5 },
  "Fife": { avgHighF: 54, avgLowF: 43, rainfallIn: 2.8, daylightHrs: 10.5 },
  "Glasgow City": { avgHighF: 55, avgLowF: 45, rainfallIn: 4.5, daylightHrs: 10.5 },
  "Highland": { avgHighF: 52, avgLowF: 41, rainfallIn: 5.9, daylightHrs: 10 },
  "Inverclyde": { avgHighF: 55, avgLowF: 45, rainfallIn: 5.5, daylightHrs: 10.5 },
  "Midlothian": { avgHighF: 54, avgLowF: 43, rainfallIn: 3.0, daylightHrs: 10.5 },
  "Moray": { avgHighF: 54, avgLowF: 41, rainfallIn: 2.8, daylightHrs: 10 },
  "North Ayrshire": { avgHighF: 55, avgLowF: 45, rainfallIn: 4.7, daylightHrs: 10.5 },
  "North Lanarkshire": { avgHighF: 54, avgLowF: 43, rainfallIn: 4.3, daylightHrs: 10.5 },
  "Orkney Islands": { avgHighF: 54, avgLowF: 45, rainfallIn: 3.5, daylightHrs: 10 },
  "Perth and Kinross": { avgHighF: 54, avgLowF: 41, rainfallIn: 3.9, daylightHrs: 10.5 },
  "Renfrewshire": { avgHighF: 54, avgLowF: 45, rainfallIn: 5.1, daylightHrs: 10.5 },
  "Scottish Borders": { avgHighF: 54, avgLowF: 41, rainfallIn: 3.1, daylightHrs: 10.5 },
  "Shetland Islands": { avgHighF: 52, avgLowF: 43, rainfallIn: 5.1, daylightHrs: 9.5 },
  "South Ayrshire": { avgHighF: 55, avgLowF: 45, rainfallIn: 4.3, daylightHrs: 10.5 },
  "South Lanarkshire": { avgHighF: 54, avgLowF: 41, rainfallIn: 4.7, daylightHrs: 10.5 },
  "Stirling": { avgHighF: 54, avgLowF: 41, rainfallIn: 5.1, daylightHrs: 10.5 },
  "West Dunbartonshire": { avgHighF: 54, avgLowF: 45, rainfallIn: 5.5, daylightHrs: 10.5 },
  "West Lothian": { avgHighF: 54, avgLowF: 43, rainfallIn: 3.1, daylightHrs: 10.5 },
}

export default CLIMATE_DATA
