// October climate averages for Scottish council areas
// Data compiled from Met Office and historical records
const CLIMATE_DATA = {
  "Aberdeen City": { avgHighF: 54, avgLowF: 43, rainyDaysPct: 55, daylightHrs: 10.5 },
  "Aberdeenshire": { avgHighF: 52, avgLowF: 41, rainyDaysPct: 58, daylightHrs: 10.5 },
  "Angus": { avgHighF: 54, avgLowF: 41, rainyDaysPct: 55, daylightHrs: 10.5 },
  "Argyll and Bute": { avgHighF: 54, avgLowF: 45, rainyDaysPct: 70, daylightHrs: 10.5 },
  "City of Edinburgh": { avgHighF: 55, avgLowF: 45, rainyDaysPct: 50, daylightHrs: 10.5 },
  "Clackmannanshire": { avgHighF: 54, avgLowF: 43, rainyDaysPct: 55, daylightHrs: 10.5 },
  "Dumfries and Galloway": { avgHighF: 55, avgLowF: 45, rainyDaysPct: 60, daylightHrs: 10.5 },
  "Dundee City": { avgHighF: 54, avgLowF: 43, rainyDaysPct: 52, daylightHrs: 10.5 },
  "East Ayrshire": { avgHighF: 54, avgLowF: 43, rainyDaysPct: 62, daylightHrs: 10.5 },
  "East Dunbartonshire": { avgHighF: 54, avgLowF: 43, rainyDaysPct: 60, daylightHrs: 10.5 },
  "East Lothian": { avgHighF: 55, avgLowF: 45, rainyDaysPct: 48, daylightHrs: 10.5 },
  "East Renfrewshire": { avgHighF: 54, avgLowF: 43, rainyDaysPct: 62, daylightHrs: 10.5 },
  "Eilean Siar": { avgHighF: 54, avgLowF: 46, rainyDaysPct: 68, daylightHrs: 10.5 },
  "Falkirk": { avgHighF: 54, avgLowF: 43, rainyDaysPct: 55, daylightHrs: 10.5 },
  "Fife": { avgHighF: 54, avgLowF: 43, rainyDaysPct: 52, daylightHrs: 10.5 },
  "Glasgow City": { avgHighF: 55, avgLowF: 45, rainyDaysPct: 58, daylightHrs: 10.5 },
  "Highland": { avgHighF: 52, avgLowF: 41, rainyDaysPct: 65, daylightHrs: 10 },
  "Inverclyde": { avgHighF: 55, avgLowF: 45, rainyDaysPct: 65, daylightHrs: 10.5 },
  "Midlothian": { avgHighF: 54, avgLowF: 43, rainyDaysPct: 52, daylightHrs: 10.5 },
  "Moray": { avgHighF: 54, avgLowF: 41, rainyDaysPct: 50, daylightHrs: 10 },
  "North Ayrshire": { avgHighF: 55, avgLowF: 45, rainyDaysPct: 62, daylightHrs: 10.5 },
  "North Lanarkshire": { avgHighF: 54, avgLowF: 43, rainyDaysPct: 58, daylightHrs: 10.5 },
  "Orkney Islands": { avgHighF: 54, avgLowF: 45, rainyDaysPct: 58, daylightHrs: 10 },
  "Perth and Kinross": { avgHighF: 54, avgLowF: 41, rainyDaysPct: 58, daylightHrs: 10.5 },
  "Renfrewshire": { avgHighF: 54, avgLowF: 45, rainyDaysPct: 62, daylightHrs: 10.5 },
  "Scottish Borders": { avgHighF: 54, avgLowF: 41, rainyDaysPct: 52, daylightHrs: 10.5 },
  "Shetland Islands": { avgHighF: 52, avgLowF: 43, rainyDaysPct: 62, daylightHrs: 9.5 },
  "South Ayrshire": { avgHighF: 55, avgLowF: 45, rainyDaysPct: 60, daylightHrs: 10.5 },
  "South Lanarkshire": { avgHighF: 54, avgLowF: 41, rainyDaysPct: 60, daylightHrs: 10.5 },
  "Stirling": { avgHighF: 54, avgLowF: 41, rainyDaysPct: 62, daylightHrs: 10.5 },
  "West Dunbartonshire": { avgHighF: 54, avgLowF: 45, rainyDaysPct: 65, daylightHrs: 10.5 },
  "West Lothian": { avgHighF: 54, avgLowF: 43, rainyDaysPct: 52, daylightHrs: 10.5 },
}

export default CLIMATE_DATA
